import { colors } from "./colors";

export const textStyles = {
  h1: {
    fontSize: 48,
    fontWeight: 700,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
    marginBottom: 16,
  },
  h2: {
    fontSize: 48,
    fontWeight: 400,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  h3: {
    fontSize: 36,
    fontWeight: 600,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  subtitle: {
    fontSize: 24,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  link: {
    fontSize: 24,
    fontWeight: 700,
    color: colors.link,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  button: {
    fontSize: 32,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  title: {
    fontSize: 24,
    fontWeight: 500,
    letterSpacing: "1%",
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  body: {
    fontSize: 16,
    fontWeight: 300,
    letterSpacing: "1%",
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  label: {
    fontSize: 20,
    fontWeight: 300,
    letterSpacing: "1%",
    color: colors.grayDark,
    fontFamily: "Poppins",
  },
  card: {
    fontSize: 32,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  menuItem: {
    default: {
      fontSize: 20,
      fontWeight: 300,
      color: colors.primary,
      fontFamily: "Poppins",
    },
    active: {
      fontSize: 20,
      fontWeight: 500,
      color: colors.primary,
      fontFamily: "Poppins",
      letterSpacing: "1%",
    },
  },
};
