import { colors } from "./colors";

export const textStyles = {
  headline: {
    fontSize: 80,
    fontWeight: 600,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  h1: {
    regular: {
      fontSize: 64,
      fontWeight: 400,
      color: colors.primary,
      lineHeight: "130%",
      fontFamily: "Poppins",
    },
    bold: {
      fontSize: 64,
      fontWeight: 700,
      color: colors.primary,
      lineHeight: "130%",
      fontFamily: "Poppins",
    },
  },
  h2: {
    fontSize: 42,
    fontWeight: 600,
    color: colors.primary,
    lineHeight: "130%",
    marginBottom: 28,
    fontFamily: "Poppins",
  },
  subtitle: {
    fontSize: 36,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  link: {
    fontSize: 32,
    fontWeight: 700,
    color: colors.link,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  button: {
    fontSize: 32,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  title: {
    fontSize: 24,
    fontWeight: 500,
    letterSpacing: "1%",
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  body: {
    fontSize: 20,
    fontWeight: 300,
    letterSpacing: "1%",
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  label: {
    fontSize: 20,
    fontWeight: 300,
    letterSpacing: "1%",
    color: colors.grayDark,
    fontFamily: "Poppins",
  },
  card: {
    fontSize: 32,
    fontWeight: 300,
    color: colors.primary,
    lineHeight: "130%",
    fontFamily: "Poppins",
  },
  menuItem: {
    fontSize: 24,
    fontWeight: 300,
    color: colors.primary,
    fontFamily: "Poppins",
  },
};
